FROM golang:1.22-alpine

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download

COPY . .

RUN go build -o spendaro-api cmd/main/main.go

CMD ["./spendaro-api", "-APP_ENV=development", "-debug=false"]
