name: Main Pipeline

on:
  push:
    branches:
      - 'main'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run tests
        run: make test

      - name: Build and Tag Docker image as latest
        run: |
          make build-dev-docker
          docker tag spendaro-api "${{ secrets.DOCKERHUB_USERNAME }}/spendaro-api:latest"

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Push latest Docker image to Docker Hub for production deployment
        run: docker push "${{ secrets.DOCKERHUB_USERNAME }}/spendaro-api:latest" # latest tag is used for the main branch - this is used to deploy the application to production


      # - name: Deploy to production
      #   run: |
      #     kubectl apply -f k8s/production
      #     kubectl rollout restart deployment spendaro-api
