name: Production Workflow

on:
  release:
    types:
      - created

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run tests
        run: make test

      - name: Build and Tag Docker image
        run: |
          make build-dev-docker
          docker tag spendaro-api "${{ secrets.DOCKERHUB_USERNAME }}/spendaro-api:${{ github.event.release.tag_name }}"

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Push Docker image to Docker Hub
        run: docker push "${{ secrets.DOCKERHUB_USERNAME }}/spendaro-api:${{ github.event.release.tag_name }}"
