name: Release Pipeline

on:
  release:
    types:
      - published

permissions:
  contents: write

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: develop
          fetch-depth: 0 # Fetch all branches

      - name: Run tests
        run: make test

      - name: Build and Tag Release Docker image
        run: |
          make build-dev-docker
          docker tag spendaro-api "${{ secrets.DOCKERHUB_USERNAME }}/spendaro-api:${{ github.event.release.tag_name }}"

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Push Release Docker image to Docker Hub
        run: docker push "${{ secrets.DOCKERHUB_USERNAME }}/spendaro-api:${{ github.event.release.tag_name }}"

      - name: Merge release branch into main to keep main up-to-date with each release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.email "${{ secrets.REPO_OWNER_EMAIL }}"
          git config --global user.name "${{ secrets.REPO_OWNER_USERNAME }}"
          git fetch origin
          git checkout main
          git merge develop --no-ff -m "Merge branch 'develop' into main"
          git push origin main
